### ISSUE TITLE
when run "textDet.py". there is an error

### ISSUE THREAD

**Issue by yangxuehang** [sxz8564/TextDetector#2]
Hi，Siyu
When I run 'python textDet.py', I encountered an error.  Have you ever encountered this problem, or do you know how to deal with this problem? Thank you! 
Following are the details shows. 

../data/myexpe/clf/coarse
Traceback (most recent call last):
  File "textDet.py", line 89, in <module>
    main()
  File "textDet.py", line 66, in main
    myClassifier.clf_load(coarseclfname, clfdir)
  File "/home/xhyang/textDetector-siyu/src/classifier.py", line 146, in clf_load
    self.classifier = pickle.load(open(os.path.join(clfdir, clfname)))
  File "/usr/local/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/local/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/local/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/pickle.py", line 1126, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'PresortBestSplitter'

**Comment by taneta** [comment]
I've got the same problem.
Also when I run `python use_ckmean.py` there is another problem: 

`Traceback (most recent call last):
  File "use_ckmean.py", line 93, in <module>
    main()
  File "use_ckmean.py", line 81, in main
    data = numpy.load('../../shared_data/syntheticData_img.npy')		
  File "/home/katerina/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 362, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '../../shared_data/syntheticData_img.npy'`

Seems like this project is not ready yet.

**Comment by colinhli** [comment]
Use  scikit-learn  verison:0.15
